```{r, echo=FALSE, message=FALSE, warning=FALSE}
source(file = "include/deadlines.R")

library(readxl)
library(knitr)
library(tidyverse)
library(lubridate)
```

# Course Overview {#Course_overview}

Welcome to your Research Methods 1 `r study_year` course on the MSc Psychology ODL Conversion programme! Across two semesters, we will introduce you to how psychologists use quantitative research methods to answer their research questions. There are many components that go into understanding and applying the techniques you will learn about, so throughout year 1 of your MSc we will cover fundamental research methods and statistics concepts, data skills to work with quantitative psychology data, and research skills to develop your understanding of reading and writing quantitative psychology reports. 

This book provides supporting information for the course such as the assignments you will complete, and resources to support developing research and writing skills. Please take the time at the start of the course to read the following course overview and learn where your sources of support are. You will keep referring back to this book throughout the year as you build your academic, research, and data skills

## Intended Learning Outcomes

By the end of the course, you will be able to:

- Understand and apply the principles of open and reproducible science;

- Generate and explore hypotheses and research questions for experimental and observational research;

- Select appropriate research designs and methodologies for different research questions;

- Demonstrate critical awareness of the assumptions of these methods and analyses and the limitations associated with experimental and observational research designs;

- Identify the ethical issues involved in experimental and observational research;

- Work as a group to plan and execute a small-scale research project using quantitative research methods;

- Demonstrate critical analysis, evaluation, and synthesis of ideas;

- Use the programming language R to conduct a range of descriptive and inferential statistics.

## Assessments

- **MCQs (5%)**

    - Answer Multiple Choice Questions (MCQs) related to content covered in weeks 1-5 including lectures and data skills.

- **Data skills portfolio (15%)**

    - Two data skills worksheets using R/RStudio, each worth 7.5%.

- **Stage one group report (30%)**

    - Group submission of a planned introduction and method to answer a research question you develop. 

 - **Stage two individual report (50%)** 
 
    - Individual submission of an abstract, results, and discussion that address the research question you developed in your group. 

Please check the Assessment and Feedback Information Sheet chapters for detailed information and deadlines.

## Course overview

Below is a provisional order of content for this course. We will notify you of any changes in advance, but feel free to read ahead to help you plan:

Download this Word file: [RM1 ODL Semester 1 Timetable 2024/2025](Supporting/RM1_ODL_Sem1_Timetable_2425.docx)

**Last updated:** 18/09/2024

## Available support

There is a lot of support in this course to help you build your knowledge and understanding of quantitative research methods and statistics. You do not have to use all the different sources of support, and some will work better for you than others will. Part of learning is about finding what helps you best. Below are a few of the main approaches we have on this course to help you and if in doubt, please just ask:

- Teams channel for discussion, questions, and support;

- Student Office Hours (sometimes called Student Drop-in Hours) - just turn up and ask anything;

- Assessment information sheets and common questions and answer documents to support assignments.

The best approach is to write down your questions when they come up, check the available material for answers, and if you are still unsure after that, use one of the approaches above.

However, please note we would ask that you do not send questions, either about a topic or an assignment, as a direct message on Teams to an individual staff member. While we always want to help, this approach is not sustainable and there is a highly likely chance your question will get missed and go unanswered. We would strongly encourage you to post the question on the course Team channel, as that way staff and students have the opportunity to answer your question, and other students can benefit from the answer. Alternatively, use the student office hours to ask questions more privately.

## Believe in yourself!

This course, and the knowledge and skills we will help you learn, is new to everybody. The phrase we hear most often is "everyone else must already know this?!". If you already knew the content, you would not be on this course or programme. We have a diverse cohort of students where some come from a science background while others do not, but no one has covered this combination of quantitative research methods in psychology. It might be challenging and take some trial and error, but every single one of you can do this. 
